# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageReplaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(699, 605)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.normalSizeZoomBtn = QtWidgets.QPushButton(Form)
        self.normalSizeZoomBtn.setObjectName("normalSizeZoomBtn")
        self.gridLayout.addWidget(self.normalSizeZoomBtn, 4, 0, 1, 1)
        self.openImageButton = QtWidgets.QPushButton(Form)
        self.openImageButton.setObjectName("openImageButton")
        self.gridLayout.addWidget(self.openImageButton, 3, 1, 1, 1)
        self.zoomInBtn = QtWidgets.QPushButton(Form)
        self.zoomInBtn.setObjectName("zoomInBtn")
        self.gridLayout.addWidget(self.zoomInBtn, 2, 0, 1, 1)
        self.zoomOutBtn = QtWidgets.QPushButton(Form)
        self.zoomOutBtn.setObjectName("zoomOutBtn")
        self.gridLayout.addWidget(self.zoomOutBtn, 3, 0, 1, 1)
        self.replaceImageButton = QtWidgets.QPushButton(Form)
        self.replaceImageButton.setEnabled(False)
        self.replaceImageButton.setObjectName("replaceImageButton")
        self.gridLayout.addWidget(self.replaceImageButton, 3, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 675, 476))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.image.setGeometry(QtCore.QRect(11, 11, 614, 393))
        self.image.setMinimumSize(QtCore.QSize(200, 200))
        self.image.setText("")
        self.image.setObjectName("image")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 5, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.normalSizeZoomBtn.setText(_translate("Form", "Обычный размер"))
        self.openImageButton.setText(_translate("Form", "Открыть картинку на замену"))
        self.zoomInBtn.setText(_translate("Form", "Приблизить картинку"))
        self.zoomOutBtn.setText(_translate("Form", "Отдалить картинку"))
        self.replaceImageButton.setText(_translate("Form", "Заменить исходную картинку на текущую открытую"))
